### ISSUE TITLE
Consider Email Suite

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-infra#15]
Mailgun switched to a paid only plan and doesnt work very smoothly.

Let's consider one of the following: 
* https://cuttlefish.io/
* https://postal.atech.media/

**Comment by NicolasDorier** [comment]
self hosting mailbox is super hard. I don't know if that's good idea.

**Comment by pavlenex** [comment]
I've e-mailed Protonmail and they don't offer a free account for open-source/non-profits. They offer 50% off on their current plans. Gmail suit seems to require insane amount of paperwork.

@Kukks when does `Mailgun` actually discontinue the support? Will look into other providers. Easy DNS which we use as btcpayserver.org has [mailboxes](https://easydns.com/email/easymail-hosted-imap/) as well, but we'd still need some sort of a cloud for files etc.

**Comment by Kukks** [comment]
> 
> 
> I've e-mailed Protonmail and they don't offer a free account for open-source/non-profits. They offer 50% off on their current plans. Gmail suit seems to require insane amount of paperwork.
> 
> @Kukks when does `Mailgun` actually discontinue the support? Will look into other providers. Easy DNS which we use as btcpayserver.org has mailboxes but by reading quickly it seems pricey and clunky.

I already switched to a paid plan so no rush. I only paid <1usd for last month at over 1k emails sent lol

**Comment by pavlenex** [comment]
Ah okay. Well personally on my end, the current system works. I really wish we had a proper mailbox but the forwarding we have in place is decent enough if we don't want to go into mailboxes. It's just clunky to set up and deliverability may not be as reliable, but for the past few weeks I haven't noticed any issues.

**Comment by Kukks** [comment]
One issue we have is that since they migrated us from a free plan, they put
us on a heavily discounted one but with MUCH less flexibility. Basically,
if we needed to add more or modify  forwarding rules, we would need to
upgrade the plan..

**Comment by NicolasDorier** [comment]
Having your own mail server is super hard. This is a job by itself.
One of the problem is that most of your mail will end up in spam boxes.
